spring.application.name=RatingService



server.port=8083



# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Microservies

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Actuator (Optional)
management.endpoints.web.exposure.include=*

# Jackson Configuration (Optional)
spring.jackson.serialization.indent-output=true